[build]
  command = "yarn build"
  publish = "dist"

[[redirects]]
	from = "https://thermal.netlify.com/*"
	to = "https://thermal.codecarrot.net/:splat"
	status = 301
	force = true

[[redirects]]
	from = "/*"
	to = "/404"
	status = 404
	force = false
